### ISSUE TITLE
(PVR) EPG Guide Play Button

### ISSUE THREAD

**Issue by cyberluke** [gade01/skin.tetradui#14]
Hi, I have tested 19.4 Matrix with PVR and it works! EPG record & play works. Switching channels works.

The only error I have found is:
1) In original Kodi skin -> choose TV -> click Guide -> choose some programme in the past -> click on 2nd button Play programme -> works

2) In TetradUI you have same behavior, but the last step click on Play programme does nothing, nothing is in the logs. It looks like this button is not being correctly mapped to the same action as original Kodi skin.

I was thinking it is a  bug in PVR plugin, but I have identified it is a bug in this skin.

Would you know in which file I could fix it? I would compare it with original Kodi definition.

**Comment by gade01** [comment]
Hi @cyberluke 

Sorry for not answering for a long time.

I'm glad you're using the skin and that it works.
We have bug plans for future updates :)

Thanks so much for reporting the issue and for the detailed description.

The issue has been fixed. The button used a wrong button ID. ;)

Thanks again.
Don't hesitate to report any bugs or issues in the future.
