### ISSUE TITLE
Weather dew point italian

### ISSUE THREAD

**Issue by mapi68** [gade01/skin.tetradui#18]
Hello, can you enlarge Dew Point from Weather window?
In italian is "Punto di rugiada"

![224582311-95cff147-843a-4fdd-bc88-67773df80efb](https://user-images.githubusercontent.com/41143572/224876434-3b7c0b5a-f5a1-4eb2-bd93-24ea5bff0d16.png)

**Comment by gade01** [comment]
Hi @mapi68 

Sorry for not answering for a while.

The issue has been fixed here: https://github.com/gade01/skin.tetradui/commit/007d43791db9e699802c421abec23b4279c723f7

Thanks so much for reporting it ;)
